### ISSUE TITLE
ignore_keys configuration documentation / implementation

### ISSUE THREAD

**Issue by schnika** [tolk/tolk#156]
**version 3.2.1**

The docs say:

```
config.ignore_keys = ['faker', 'devise']
# Ignore all faker.* and devise.* keys
```

## Current steup

You can reproduce it with this test steup:

_test/unit/sync_test.rb_

```
  def test_sync_ignore_keys
    Tolk.config.ignore_keys = %w[anything_at_first_place_is_important ignored nested.ignored ]

    Tolk::Locale.sync!

    phrase = Tolk::Phrase.all.detect {|p| p.key == 'ignored'}
    assert_nil phrase

    phrase = Tolk::Phrase.all.detect {|p| p.key == 'nested.ignored'}
    assert_nil phrase

    phrase = Tolk::Phrase.all.detect {|p| p.key == 'includesignored'}
    assert_equal 'includesignored', phrase.key
  end
```

_test/locales/sync/en.yml_

```
---
en:
  nested:
    hello_country: Nested Hello Country
    ignored: This should be ignored
  hello_world: Hello World
  i18n:
    plural: Locale specific pluralization rules
  ignored: This should be ignored
  includesignored: This should not be ignored
```

```
~/.../forks/tolk >>> bin/rails test test/unit/sync_test.rb                                                                                                                        ±[●●][master]
Run options: --seed 32283

# Running:

...........F

Failure:
SyncTest#test_sync_ignore_keys [/home/patrick/projects/gems/tolk/test/unit/sync_test.rb:240]:
Expected: "includesignored"
  Actual: nil
```

## Solution 1

make sure that the regexp in sync.rb actually builds the "correct" regexp.

e.g `regexp = Regexp.new(/\A(#{ignored_escaped.join('|')})\Z/)`

## Solution 2

Change the docs because what i encounter is the expected behaviour.
